export const GET_PRODUCT_LIST_START = "GET_PRODUCT_LIST_START";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_FAIL =  "GET_PRODUCT_LIST_FAIL";

export const DELETE_PRODUCT_LIST_START = "DELETE_PRODUCT_LIST_START";
export const DELETE_PRODUCT_LIST_SUCCESS = "DELETE_PRODUCT_LIST_SUCCESS";
export const DELETE_PRODUCT_LIST_FAIL =  "DELETE_PRODUCT_LIST_FAIL";

export const SAVE_PRODUCT_LIST_START = "SAVE_PRODUCT_LIST_START";
export const SAVE_PRODUCT_LIST_SUCCESS = "SAVE_PRODUCT_LIST_SUCCESS";
export const SAVE_PRODUCT_LIST_FAIL =  "SAVE_PRODUCT_LIST_FAIL";